Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\ProgramData\Miniconda3\lib\site-packages\nbclient\client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\ProgramData\Miniconda3\lib\site-packages\jupyter_core\utils\__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "C:\ProgramData\Miniconda3\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\ProgramData\Miniconda3\lib\site-packages\nbclient\client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "C:\ProgramData\Miniconda3\lib\site-packages\nbclient\client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\ProgramData\Miniconda3\lib\site-packages\nbclient\client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
questions = get_user_information("questions")
questions = questions.rename(columns=questions.iloc[0]).drop(questions.index[0])
questions['question_created'] = datetime.now()
------------------


[1;31m---------------------------------------------------------------------------[0m
[1;31mFileNotFoundError[0m                         Traceback (most recent call last)
Cell [1;32mIn[3], line 1[0m
[1;32m----> 1[0m questions [38;5;241m=[39m [43mget_user_information[49m[43m([49m[38;5;124;43m"[39;49m[38;5;124;43mquestions[39;49m[38;5;124;43m"[39;49m[43m)[49m
[0;32m      2[0m questions [38;5;241m=[39m questions[38;5;241m.[39mrename(columns[38;5;241m=[39mquestions[38;5;241m.[39miloc[[38;5;241m0[39m])[38;5;241m.[39mdrop(questions[38;5;241m.[39mindex[[38;5;241m0[39m])
[0;32m      3[0m questions[[38;5;124m'[39m[38;5;124mquestion_created[39m[38;5;124m'[39m] [38;5;241m=[39m datetime[38;5;241m.[39mnow()

Cell [1;32mIn[2], line 4[0m, in [0;36mget_user_information[1;34m(sheet_name)[0m
[0;32m      1[0m [38;5;28;01mdef[39;00m [38;5;21mget_user_information[39m(sheet_name):
[0;32m      2[0m   scope [38;5;241m=[39m [[38;5;124m'[39m[38;5;124mhttps://spreadsheets.google.com/feeds[39m[38;5;124m'[39m,[38;5;124m'[39m[38;5;124mhttps://www.googleapis.com/auth/drive[39m[38;5;124m'[39m]
[1;32m----> 4[0m   creds [38;5;241m=[39m [43mServiceAccountCredentials[49m[38;5;241;43m.[39;49m[43mfrom_json_keyfile_name[49m[43m([49m[38;5;124;43m'[39;49m[38;5;124;43mcreds.json[39;49m[38;5;124;43m'[39;49m[43m,[49m[43mscope[49m[43m)[49m
[0;32m      6[0m   client [38;5;241m=[39m gspread[38;5;241m.[39mauthorize(creds)
[0;32m      8[0m   industries [38;5;241m=[39m client[38;5;241m.[39mopen([38;5;124m"[39m[38;5;124mquizs[39m[38;5;124m"[39m)[38;5;241m.[39mworksheet(sheet_name)

File [1;32mC:\ProgramData\Miniconda3\lib\site-packages\oauth2client\service_account.py:219[0m, in [0;36mServiceAccountCredentials.from_json_keyfile_name[1;34m(cls, filename, scopes, token_uri, revoke_uri)[0m
[0;32m    193[0m [38;5;129m@classmethod[39m
[0;32m    194[0m [38;5;28;01mdef[39;00m [38;5;21mfrom_json_keyfile_name[39m([38;5;28mcls[39m, filename, scopes[38;5;241m=[39m[38;5;124m'[39m[38;5;124m'[39m,
[0;32m    195[0m                            token_uri[38;5;241m=[39m[38;5;28;01mNone[39;00m, revoke_uri[38;5;241m=[39m[38;5;28;01mNone[39;00m):
[0;32m    197[0m [38;5;250m    [39m[38;5;124;03m"""Factory constructor from JSON keyfile by name.[39;00m
[0;32m    198[0m 
[0;32m    199[0m [38;5;124;03m    Args:[39;00m
[1;32m   (...)[0m
[0;32m    217[0m [38;5;124;03m            the keyfile.[39;00m
[0;32m    218[0m [38;5;124;03m    """[39;00m
[1;32m--> 219[0m     [38;5;28;01mwith[39;00m [38;5;28;43mopen[39;49m[43m([49m[43mfilename[49m[43m,[49m[43m [49m[38;5;124;43m'[39;49m[38;5;124;43mr[39;49m[38;5;124;43m'[39;49m[43m)[49m [38;5;28;01mas[39;00m file_obj:
[0;32m    220[0m         client_credentials [38;5;241m=[39m json[38;5;241m.[39mload(file_obj)
[0;32m    221[0m     [38;5;28;01mreturn[39;00m [38;5;28mcls[39m[38;5;241m.[39m_from_parsed_json_keyfile(client_credentials, scopes,
[0;32m    222[0m                                          token_uri[38;5;241m=[39mtoken_uri,
[0;32m    223[0m                                          revoke_uri[38;5;241m=[39mrevoke_uri)

[1;31mFileNotFoundError[0m: [Errno 2] No such file or directory: 'creds.json'

